INSERT INTO USER(DNI) VALUES('43170873B');
INSERT INTO USER(DNI) VALUES('19843446N');
INSERT INTO USER(DNI) VALUES('58519841K');
INSERT INTO USER(DNI) VALUES('76774376P');
INSERT INTO USER(DNI) VALUES('22232576V');

INSERT INTO ITINERARY(CODE) VALUES('BE');
INSERT INTO ITINERARY(CODE) VALUES('FE');
INSERT INTO ITINERARY(CODE) VALUES('AD');

INSERT INTO VIDEO(ID, NAME, ITINERARY_CODE) VALUES(1, 'Java Intro Video', 'BE');
INSERT INTO VIDEO(ID, NAME, ITINERARY_CODE) VALUES(2, 'OOP Basics Video', 'BE');
INSERT INTO VIDEO(ID, NAME, ITINERARY_CODE) VALUES(3, 'Java Intro Video ', 'AD');
INSERT INTO VIDEO(ID, NAME, ITINERARY_CODE) VALUES(4, 'HTML5 Intro Video', 'FE');
INSERT INTO VIDEO(ID, NAME, ITINERARY_CODE) VALUES(5, 'JavaScript Intro Video', 'FE');

INSERT INTO EXERCISE(ID, NAME, ITINERARY_CODE) VALUES(1, 'Java Basics Exercise 1', 'BE');
INSERT INTO EXERCISE(ID, NAME, ITINERARY_CODE) VALUES(2, 'Java Basics Exercise 2', 'BE');
INSERT INTO EXERCISE(ID, NAME, ITINERARY_CODE) VALUES(3, 'Java Basics Exercise 3', 'BE');
INSERT INTO EXERCISE(ID, NAME, ITINERARY_CODE) VALUES(4, 'JavaScript DOM Basics Exercise', 'FE');
INSERT INTO EXERCISE(ID, NAME, ITINERARY_CODE) VALUES(5, 'My First Android App Exercise', 'AD');
